url: '/clients/thecostumegames.com/_site/'
cdn: '/clients/thecostumegames.com/_site/'
assets:
    sources:
        - _assets/images
        - _assets/javascripts
        - _assets/stylesheets
        - _media
    baseurl: "/clients/thecostumegames.com/_site/assets"
    cache: false
    js_compressor: false
    css_compressor: false
    gzip: false