url: '/clients/thecostumegames.com/new/_site/'
cdn: '/clients/thecostumegames.com/new/_site/'
assets:
    sources:
        - _assets/images
        - _assets/javascripts
        - _assets/stylesheets
        - images
    baseurl: "/clients/thecostumegames.com/new/_site/assets"
    cache: false
    js_compressor: false
    css_compressor: false
    gzip: false